mod_version=1.0.0.0
root_package=com.stepm.techgunsupgrade
mod_id=techgunsupgrade
mod_name=Techguns Upgrade
mod_authors=Steparm_tesst
mod_description=Upgrade station for Techguns weapons with random buffs!

use_modern_java_syntax=false
mapping_channel=stable
mapping_version=39

use_mixins=true
mixin_booter_version=11.13
mixin_refmap=mixins.techgunsupgrade.refmap.json
mixin_package=com.stepm.techgunsupgrade.mixin
mixin_configs=techgunsupgrade
generate_mixins_json=true

use_tags=false
tag_class_name=com.stepm.techgunsupgrade.Tags
use_access_transformer=false
access_transformer_locations=
is_coremod=false
coremod_includes_mod=false
coremod_plugin_class_name=com.stepm.techgunsupgrade.core.UpgradeCoreMod
use_asset_mover=false
asset_mover_version=
use_dependency_at_files=true
minecraft_username=Developer
extra_jvm_args=
extra_tweak_classes=
change_minecraft_sources=false
use_jetbrains_annotations=false
generate_sources_jar=true
generate_javadocs_jar=true
enable_junit_testing=true
show_testing_output=false
publish_to_maven=false
publish_to_local_maven=false
publish_to_curseforge=false
publish_to_modrinth=false
